# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aritle',
            new_name='Article',
        ),
    ]
