# Generated by Django 2.0.4 on 2018-07-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_time']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='tilte',
            new_name='title',
        ),
    ]
