# Generated by Django 2.0.7 on 2018-09-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
