# Generated by Django 2.0.7 on 2018-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtype_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_name', models.CharField(max_length=50)),
                ('net_link', models.URLField()),
            ],
        ),
    ]
