# Generated by Django 2.0.7 on 2018-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180827_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='url',
            field=models.URLField(),
        ),
    ]
