# Generated by Django 2.0.7 on 2018-08-30 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180830_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='is_bind',
            field=models.BooleanField(verbose_name='邮箱绑定'),
        ),
        migrations.AlterField(
            model_name='usrinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='邮箱绑定'),
        ),
    ]
