# Generated by Django 2.0.7 on 2018-09-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20180909_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='root_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
