# Generated by Django 2.0.7 on 2018-09-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_root_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='root_object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
