# Generated by Django 2.0.7 on 2018-09-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_comment_root_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='root_id',
        ),
    ]
