# Generated by Django 2.0.7 on 2018-09-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_auto_20180917_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='root',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='root_id',
            field=models.IntegerField(default=0),
        ),
    ]
