# Generated by Django 2.0.7 on 2018-09-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_auto_20180918_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to_id',
        ),
    ]
